version: '3'

networks:
  devnetwork:
    external: true
volumes:
  postgres:
  
services:
 concourse-db:
   image: postgres:9.5
   networks: 
      - devnetwork
   volumes:
    - postgres:/var/lib/postgresql/data
   environment:
     POSTGRES_DB: concourse
     POSTGRES_USER: concourse
     POSTGRES_PASSWORD: changeme
    
 concourse-web:
   image: concourse/concourse
   networks: 
      devnetwork: 
   command: web
   ports: ["8087:8080"]
   volumes: ["./keys/web:/concourse-keys"]
   environment:
     CONCOURSE_BASIC_AUTH_USERNAME: concourse
     CONCOURSE_BASIC_AUTH_PASSWORD: changeme
     CONCOURSE_EXTERNAL_URL: "${CONCOURSE_EXTERNAL_URL}"
     CONCOURSE_POSTGRES_DATA_SOURCE: |-
       postgres://concourse:changeme@concourse-db:5432/concourse?sslmode=disable
 
 concourse-worker:
   image: concourse/concourse
   networks: 
      devnetwork: 
   privileged: true
   command: worker
   volumes: ["./keys/worker:/concourse-keys"]
   environment:
      CONCOURSE_TSA_HOST: concourse-web
      CONCOURSE_GARDEN_ADDRESS: concourse-worker
      CONCOURSE_BAGGAGECLAIM_ADDRESS: concourse-worker
      CONCOURSE_GARDEN_FORWARD_ADDRESS: concourse-worker
      CONCOURSE_BAGGAGECLAIM_FORWARD_ADDRESS: concourse-worker
      CONCOURSE_GARDEN_DNS_SERVER: 8.8.8.8
      CONCOURSE_GARDEN_DNS_SERVER: 8.8.4.4