version: '3'

networks:
  devnetwork:
    external: true
volumes:
  postgres:
  dnsmasq:
  
services:
 concourse-db:
   image: postgres:9.5
   networks: 
      devnetwork:
        ipv4_address: 172.18.0.3
   volumes:
    - postgres:/var/lib/postgresql/data
   environment:
     POSTGRES_DB: concourse
     POSTGRES_USER: concourse
     POSTGRES_PASSWORD: changeme 
   restart: always  

 concourse-web:
   build: ./web
   networks: 
      devnetwork: 
        ipv4_address: 172.18.0.4
   command: web
   ports: 
    - 8087:8080
   environment:
     CONCOURSE_BASIC_AUTH_USERNAME: concourse
     CONCOURSE_BASIC_AUTH_PASSWORD: changeme
     CONCOURSE_POSTGRES_DATA_SOURCE: |-
       postgres://concourse:changeme@concourse-db:5432/concourse?sslmode=disable
     CONCOURSE_TSA_HOST_KEY: "/concourse-keys/web/tsa_host_key"
     CONCOURSE_TSA_AUTHORIZED_KEYS: "/concourse-keys/web/authorized_worker_keys"
     CONCOURSE_SESSION_SIGNING_KEY: "/concourse-keys/web/session_signing_key"
   restart: always
 
 concourse-worker:
   build: ./worker
   networks: 
      devnetwork: 
          ipv4_address: 172.18.0.5
   privileged: true
   command: worker
   environment:
      CONCOURSE_TSA_HOST: concourse-web
      CONCOURSE_GARDEN_ADDRESS: concourse-worker
      CONCOURSE_BAGGAGECLAIM_ADDRESS: concourse-worker
      CONCOURSE_GARDEN_FORWARD_ADDRESS: concourse-worker
      CONCOURSE_BAGGAGECLAIM_FORWARD_ADDRESS: concourse-worker
      CONCOURSE_TSA_PUBLIC_KEY: "/concourse-keys/worker/tsa_host_key.pub"
      CONCOURSE_TSA_WORKER_PRIVATE_KEY: "/concourse-keys/worker/worker_key"
      CONCOURSE_GARDEN_DNS_SERVER: 172.18.0.2
   restart: always
 
 dnsmasq:
   image: jpillora/dnsmasq
   networks:
      devnetwork:
        ipv4_address: 172.18.0.2
   ports:
    - 53:52/udp
    - 5555:8080
   volumes:
     - dnsmasq:/etc
   logging:
      options:
        max-size: "100m"
   environment:
      USER: admin 
      PASS: changeme
   restart: always



